app = 'backend-red-meadow-8440'
primary_region = 'bom'

[build]

[env]
  PORT = '8080'
  GOOGLE_API_VERSION = 'v1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']


[http_service.concurrency]
  type = 'connections'
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'get'
  timeout = '5s'
  path = '/health'

[[vm]]
  memory = '1gb'
  cpus = 1